#pragma parameter COLOR_HEADER " —— Factory: Colorimetry —— " 0.0 0.0 0.0 0.0

#pragma parameter COLORIMETRY_PRESET "Colorimetry preset (off, 601, Japan, EBU, 709)" 1.0 0.0 4.0 1.0

#pragma parameter R_X "Phosphor red x" 0.630 0.0 1.0 0.001
#pragma parameter R_Y "Phosphor red y" 0.340 0.0 1.0 0.001
#pragma parameter G_X "Phosphor green x" 0.310 0.0 1.0 0.001
#pragma parameter G_Y "Phosphor green y" 0.595 0.0 1.0 0.001
#pragma parameter B_X "Phosphor blue x" 0.155 0.0 1.0 0.001
#pragma parameter B_Y "Phosphor blue y" 0.070 0.0 1.0 0.001
#pragma parameter W_X "White point x" 0.3127 0.0 1.0 0.0001
#pragma parameter W_Y "White point y" 0.3290 0.0 1.0 0.0001