#pragma parameter LIMITER_HEADER " —— Factory: Limiter —— " 0.0 0.0 0.0 0.0

#pragma parameter NTSC_CONVERSION "Use NTSC conversion matrix (off, on)" 0.0 0.0 1.0 1.0
#pragma parameter NTSC_CONVERSION_WEIGHT "NTSC conversion weight" 0.8 0.0 1.0 0.01
#pragma parameter LIMITER_TYPE "Limiter type (0=soft, 1=hard)" 0.0 0.0 1.0 1.0
#pragma parameter LIMITER_COMPRESSION_POINT "Compression point (IRE)" 100.0 0.0 140.0 1.0
#pragma parameter LIMITER_MAX_OUTPUT "Maximum output (IRE)" 110.0 0.0 140.0 1.0