#pragma parameter PHOSPHOR_HEADER " —— Factory: Phosphors —— " 0.0 0.0 0.0 0.0

#pragma parameter PHOSPHOR_MANTISSA_R "Phosphor decay mantissa R (s)" 1.0 0.0 999.0 1.0
#pragma parameter PHOSPHOR_MANTISSA_G "Phosphor decay mantissa G (s)" 100.0 0.0 999.0 1.0
#pragma parameter PHOSPHOR_MANTISSA_B "Phosphor decay mantissa B (s)" 100.0 0.0 999.0 1.0

#pragma parameter PHOSPHOR_EXPONENT_R "Phosphor decay exponent R (base-10)" -3.0 -9.0 0.0 1.0
#pragma parameter PHOSPHOR_EXPONENT_G "Phosphor decay exponent G (base-10)" -6.0 -9.0 0.0 1.0
#pragma parameter PHOSPHOR_EXPONENT_B "Phosphor decay exponent B (base-10)" -6.0 -9.0 0.0 1.0

#pragma parameter PHOSPHOR_HOLD_R "Phosphor tail hold R (order)" 0.9 0.5 2.0 0.1
#pragma parameter PHOSPHOR_HOLD_G "Phosphor tail hold G (order)" 1.2 0.5 2.0 0.1
#pragma parameter PHOSPHOR_HOLD_B "Phosphor tail hold B (order)" 1.2 0.5 2.0 0.1