#pragma parameter SYS_COMPONENT_HEADER " —— System: Component Video —— " 0.0 0.0 0.0 0.0

#pragma parameter YC_MODEL "System color space (YIQ, YPbPr, YUV, YDbDr, YCbCr)" 1.0 0.0 4.0 1.0

#pragma parameter SYS_BIAS_Y "Offset Y (IRE)" 0.0 -30.0 30.0 0.1
#pragma parameter SYS_BIAS_U "Offset U (IRE)" 0.0 -30.0 30.0 0.1
#pragma parameter SYS_BIAS_V "Offset V (IRE)" 0.0 -30.0 30.0 0.1

#pragma parameter SYS_GAIN_Y "Gain Y (dB)" 0.0 -30.0 30.0 0.1
#pragma parameter SYS_GAIN_U "Gain U (dB)" 0.0 -30.0 30.0 0.1
#pragma parameter SYS_GAIN_V "Gain V (dB)" 0.0 -30.0 30.0 0.1

#pragma parameter SYS_BANDWIDTH_Y "Bandwidth Y (MHz)" 5.4 0.0 75.0 0.01
#pragma parameter SYS_BANDWIDTH_U "Bandwidth U (MHz)" 3.6 0.0 15.0 0.01
#pragma parameter SYS_BANDWIDTH_V "Bandwidth V (MHz)" 3.6 0.0 15.0 0.01

#pragma parameter SYS_CUTOFF_ATTEN_Y "Cutoff attenuation Y (dB)" 12.5 0.0 30.0 1.0
#pragma parameter SYS_CUTOFF_ATTEN_U "Cutoff attenuation U (dB)" 20.0 0.0 30.0 1.0
#pragma parameter SYS_CUTOFF_ATTEN_V "Cutoff attenuation V (dB)" 20.0 0.0 30.0 1.0