#pragma parameter USER_GAMMA "Gamma (0.1)" 0.0 -2.0 4.0 1.0

#pragma parameter USER_H_SIZE "Horizontal size (%)" 58.4 0.0 100.0 0.1
#pragma parameter USER_V_SIZE "Vertical size (%)" 58.4 0.0 100.0 0.1

#pragma parameter USER_H_POS "Horizontal position (%)" 50.0 0.0 100.0 0.1
#pragma parameter USER_V_POS "Vertical position (%)" 50.0 0.0 100.0 0.1
#pragma parameter USER_BLUE_ONLY "Blue toggle (off, on)" 0.0 0.0 1.0 1.0
#pragma parameter USER_UNDERSCAN_TOGGLE "Underscan toggle (off, on)" 0.0 0.0 1.0 1.0