#pragma parameter USER_GAMMA "Gamma (0.1)" 0.0 -2.0 4.0 1.0

#pragma parameter USER_H_SIZE "Horizontal Size (%)" 58.4 0.0 100.0 0.1
#pragma parameter USER_V_SIZE "Vertical Size (%)" 58.4 0.0 100.0 0.1

#pragma parameter USER_H_POS "Horizontal Position (%)" 50.0 0.0 100.0 0.1
#pragma parameter USER_V_POS "Vertical Position (%)" 50.0 0.0 100.0 0.1

#pragma parameter USER_BLUE_ONLY "Blue toggle (0=Off, 1=On)" 0.0 0.0 1.0 1.0
#pragma parameter USER_UNDERSCAN_TOGGLE "Underscan toggle (0=Off, 1=On)" 0.0 0.0 1.0 1.0