// Common end-user parameters specific to non-RGB video signals

#pragma parameter USER_YUV_SETTINGS_HEADER " —— User: Video —— " 0.0 0.0 0.0 0.0

#pragma parameter USER_COLOR "Color (%)" 50.0 0.0 100.0 1.0
#pragma parameter USER_TINT "Tint (°)" 0.5 0.0 1.0 0.01
#pragma parameter USER_SHARPNESS "Sharpness (%)" 0.0 0.0 100.0 1.0

#pragma parameter USER_MONOCHROME "Monochrome toggle (0=Off, 1=On)" 0.0 0.0 1.0 1.0