#pragma parameter COLOR_HEADER " —— Output: Color Conversion —— " 0.0 0.0 0.0 0.0

#pragma parameter R_X "Phosphor red x" 0.630 0.0 1.0 0.001
#pragma parameter R_Y "Phosphor red y" 0.340 0.0 1.0 0.001
#pragma parameter G_X "Phosphor green x" 0.310 0.0 1.0 0.001
#pragma parameter G_Y "Phosphor green y" 0.595 0.0 1.0 0.001
#pragma parameter B_X "Phosphor blue x" 0.155 0.0 1.0 0.001
#pragma parameter B_Y "Phosphor blue y" 0.070 0.0 1.0 0.001

#pragma parameter R_WEIGHT "Red weight" 0.2124 0.0 1.0 0.0001
#pragma parameter G_WEIGHT "Green weight" 0.7011 0.0 1.0 0.0001
#pragma parameter B_WEIGHT "Blue weight" 0.0866 0.0 1.0 0.0001

#pragma parameter COLOR_CONVERSION_METHOD "Chromatic adaptation (N,Brad,MBrad,Z-L)" 0.0 0.0 3.0 1.0

#pragma parameter TONE_MAP_HEADER " —— Output: Tone Mapping —— " 0.0 0.0 0.0 0.0

#pragma parameter TONE_MAP_TYPE "Tone Mapping Type (R,RY,RX,RXY,U2,ACES)" 3.0 0.0 5.0 1.0