#pragma parameter SERVICE_GEOMETRY_HEADER " —— Service: Geometry —— " 0.0 0.0 0.0 0.0

#pragma parameter UNDERSCAN "Underscan (%)" 10.0 0.0 20.0 0.1
#pragma parameter FOCUS "Beam focus (%)" 25.0 0.0 100.0 1.0
#pragma parameter S_CORRECTION_H "Horizontal S-correction (%)" 0.0 -100.0 100.0 1.0
#pragma parameter S_CORRECTION_V "Vertical S-correction (%)" 0.0 -100.0 100.0 1.0
#pragma parameter TRAPEZOIDAL_CORRECTION "Trapezoidal correction (%)" 0.0 -100.0 100.0 1.0
#pragma parameter CORNER_CORRECTION "Corner correction (%)" 0.0 0.0 100.0 1.0
#pragma parameter MAGNETIC_CORRECTION "Magnetic correction (%)" 50.0 0.0 100.0 1.0